# Generated by Django 2.1.3 on 2018-11-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('nombremayuscula', models.CharField(blank=True, max_length=30)),
                ('padre', models.CharField(default='', max_length=30)),
                ('tipo', models.CharField(default='', max_length=1)),
                ('nombretipo', models.CharField(default='', max_length=15)),
                ('largostring', models.SmallIntegerField(default=0)),
                ('foranea', models.CharField(default='', max_length=30)),
                ('inicial', models.CharField(default='', max_length=30)),
                ('mensaje', models.TextField(default='')),
                ('codigo', models.TextField(default='')),
                ('etiqueta', models.CharField(max_length=100)),
                ('nombreself', models.CharField(max_length=100)),
                ('textobotones', models.CharField(max_length=100)),
                ('primero', models.BooleanField(default='False')),
            ],
        ),
    ]
