# Generated by Django 2.1.3 on 2018-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crear',
            name='ide',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
