# Generated by Django 2.1.3 on 2018-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear', '0003_auto_20181205_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear',
            name='aplicacionid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crear',
            name='modeloid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crear',
            name='propiedadid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crear',
            name='proyectoid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crear',
            name='reglaid',
            field=models.IntegerField(default=0),
        ),
    ]
