# Generated by Django 2.1.3 on 2018-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear', '0004_auto_20181205_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='crear',
            name='identa',
            field=models.IntegerField(default=0),
        ),
    ]
