# Generated by Django 2.1.3 on 2018-12-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear', '0005_crear_identa'),
    ]

    operations = [
        migrations.AddField(
            model_name='crear',
            name='restoidenta',
            field=models.IntegerField(default=0),
        ),
    ]
