# Generated by Django 2.1.3 on 2018-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='altopixeles',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='anchopixeles',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='justificacion',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='numerocolumnas',
            field=models.SmallIntegerField(default=3),
        ),
    ]
