# Generated by Django 2.1.3 on 2018-11-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20181128_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='colortitulo',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fonttitulo',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='justificaciontitulo',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='numerocolumnastitulo',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='textotitulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
