# Generated by Django 2.1.3 on 2018-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20181128_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='altomenu',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colorfondomenu',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colormenu',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fontmenu',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='mayusculas',
            field=models.BooleanField(default=True),
        ),
    ]
