# Generated by Django 2.1.3 on 2018-11-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20181128_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='existederecha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='existeizquierda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='numerocolumnascentro',
            field=models.SmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='numerocolumnasderecha',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='numerocolumnasizquierda',
            field=models.SmallIntegerField(default=0),
        ),
    ]
