# Generated by Django 2.1.3 on 2018-11-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20181128_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='columnasdivision',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='numerodivisionespie',
            field=models.SmallIntegerField(default=12),
        ),
    ]
