# Generated by Django 2.1.3 on 2018-11-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20181128_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='columnasderechaencabezado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='columnasizquierdaencabezado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='existederechaencabezado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='existeizquierdaencabezado',
            field=models.BooleanField(default=True),
        ),
    ]
