# Generated by Django 2.1.3 on 2018-11-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20181129_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='existederechaencabezado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='existeizquierdaencabezado',
        ),
    ]
