# Generated by Django 2.1.3 on 2018-11-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20181129_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='listafontsgoogle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
