# Generated by Django 2.1.3 on 2018-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_proyecto_listafontsgoogle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='listafontsgoogle',
            field=models.CharField(max_length=200),
        ),
    ]
