# Generated by Django 2.1.3 on 2018-11-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_auto_20181129_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='existederecha',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='existeizquierda',
        ),
    ]
