# Generated by Django 2.1.3 on 2018-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_auto_20181130_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='textoopcioninicio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
