# Generated by Django 2.1.3 on 2018-12-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_proyecto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='altocabezado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colorfondoencabezado',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='justificacionverticallogo',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='justificacionverticaltitulo',
            field=models.CharField(default='c', max_length=1),
        ),
    ]
