# Generated by Django 2.1.3 on 2018-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_auto_20181207_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='altocabezado',
            field=models.SmallIntegerField(default=100),
        ),
    ]
