# Generated by Django 2.1.3 on 2018-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_auto_20181207_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='avatartitulo',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colorfondologo',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colorfondotitulo',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
