# Generated by Django 2.1.3 on 2018-12-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_auto_20181207_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='altocabezado',
            new_name='altoencabezado',
        ),
    ]
