# Generated by Django 2.1.3 on 2018-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_auto_20181207_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='colorhovermenu',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
