# Generated by Django 2.1.3 on 2018-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_proyecto_colorhovermenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tienecolorhover',
            field=models.BooleanField(default=False),
        ),
    ]
