# Generated by Django 2.1.3 on 2018-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_proyecto_tienecolorhover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='textotitulo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
