# Generated by Django 2.1.3 on 2018-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_auto_20181209_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='altopixelestitulo',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='anchopixelestitulo',
            field=models.SmallIntegerField(default=100),
        ),
    ]
