# Generated by Django 2.1.3 on 2018-12-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_auto_20181209_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tituloizquierda',
            field=models.BooleanField(default=False),
        ),
    ]
