# Generated by Django 2.1.3 on 2018-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_proyecto_tituloizquierda'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='conseguridad',
            field=models.BooleanField(default=False),
        ),
    ]
