# Generated by Django 2.1.3 on 2018-11-20 19:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Primer nombre')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('padre', models.CharField(default='nada', max_length=30)),
                ('nombreself', models.CharField(max_length=100)),
                ('nombreborrar', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.Aplicacion')),
            ],
        ),
    ]
