# Generated by Django 2.1.3 on 2018-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='altotitulolistahijos',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='bordeinferior',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colorcolumnas',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colorcolumnaslistahijos',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='coloreditarborrar',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colorfondotitulolista',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colorfondotitulolistahijos',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colorlinknuevo',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colortextoborrado',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colortextolistahijos',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colortitulolista',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='columnaspordivision',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='controlesautomaticos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fontcolumnas',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fontecolumnaslistahijos',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fonteditarborrar',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fontelinknuevo',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fontetextoborrado',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fontetextotitulolistahijos',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fonttitulolista',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='hijoscontiguos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='justificacioncolumnas',
            field=models.CharField(default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='justificacioncolumnaslistahijos',
            field=models.CharField(default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='justificaciontitulolista',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='mayusculascolumnas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='mayusculascolumnaslistahijos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='mayusculastitulolista',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='nombretitulopagina',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='numerodivisiones',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='textoborrado',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='textobotonborrado',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='textoeditarborrar',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='textolinknuevo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='textotitulolistahijos',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='titulolista',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
