# Generated by Django 2.1.3 on 2018-11-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_auto_20181129_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='fontecolumnaslistahijos',
            new_name='fontcolumnaslistahijos',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='fontetextoborrado',
            new_name='fonttextoborrado',
        ),
    ]
