# Generated by Django 2.1.3 on 2018-11-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20181129_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='fontelinknuevo',
            new_name='fontlinknuevo',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='fontetextotitulolistahijos',
            new_name='fonttextotitulolistahijos',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='nombretitulopagina',
            new_name='textotitulopagina',
        ),
    ]
