# Generated by Django 2.1.3 on 2018-11-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20181129_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='numerocolumnasderechaedicion',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='numerocolumnashijosedicion',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='numerocolumnasizquierdaedicion',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='numerocolumnasmodeloedicion',
            field=models.SmallIntegerField(default=1),
        ),
    ]
