# Generated by Django 2.1.3 on 2018-12-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_auto_20181130_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='colortextotitulopagina',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fonttextotitulopagina',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
    ]
