# Generated by Django 2.1.3 on 2018-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_auto_20181201_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='coloretiqueta',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='etiquetaarriba',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fontetiqueta',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
    ]
