# Generated by Django 2.1.3 on 2018-12-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_modelo_altotitulolista'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='justificaciontitulolistahijos',
            field=models.CharField(default='i', max_length=1),
        ),
    ]
