# Generated by Django 2.1.3 on 2018-12-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_modelo_justificaciontitulolistahijos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='altotitulolista',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='altotitulolistahijos',
        ),
    ]
