# Generated by Django 2.1.3 on 2018-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0010_auto_20181202_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='mayusculastitulolistahijos',
            field=models.BooleanField(default=True),
        ),
    ]
