# Generated by Django 2.1.3 on 2018-12-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0011_modelo_mayusculastitulolistahijos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='colorcolumnaslistahijos',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='fontcolumnaslistahijos',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='justificacioncolumnaslistahijos',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='mayusculascolumnaslistahijos',
        ),
    ]
