# Generated by Django 2.1.3 on 2018-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0012_auto_20181202_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='colorcolumnaslistahijos',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fontcolumnaslistahijos',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='mayusculascolumnaslistahijos',
            field=models.BooleanField(default=True),
        ),
    ]
