# Generated by Django 2.1.3 on 2018-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0013_auto_20181202_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='textoopcionmenu',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
