# Generated by Django 2.1.3 on 2018-12-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0014_modelo_textoopcionmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='justificacioncolumnas',
        ),
    ]
