# Generated by Django 2.1.3 on 2018-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0015_remove_modelo_justificacioncolumnas'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='fondocolumnaslistahijos',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
