# Generated by Django 2.1.3 on 2018-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0016_modelo_fondocolumnaslistahijos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='columnaspordivision',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='numerodivisiones',
        ),
        migrations.AlterField(
            model_name='modelo',
            name='textoborrado',
            field=models.CharField(default='Desea borrar el registro', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='textobotonborrado',
            field=models.CharField(default='Borrar', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='textoeditarborrar',
            field=models.CharField(default='Editar,Borrar', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='textolinknuevo',
            field=models.CharField(default='Nuevo registro', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='textoopcionmenu',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='textotitulolistahijos',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='textotitulopagina',
            field=models.CharField(default='Nuevo registro', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='titulolista',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
