# Generated by Django 2.1.3 on 2018-12-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_proyecto_usuario'),
        ('modelos', '0017_auto_20181206_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto'),
            preserve_default=False,
        ),
    ]
