# Generated by Django 2.1.3 on 2018-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0018_modelo_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='numerocolumnasderechanuevo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='numerocolumnashijosnuevo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='numerocolumnasizquierdanuevo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modelo',
            name='numerocolumnasmodelonuevo',
            field=models.SmallIntegerField(default=1),
        ),
    ]
