# Generated by Django 2.1.3 on 2018-12-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0019_auto_20181206_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='numerocolumnashijosnuevo',
        ),
    ]
