# Generated by Django 2.1.3 on 2018-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0020_remove_modelo_numerocolumnashijosnuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='altotitulolista',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='justificacionverticaltitulolista',
            field=models.CharField(default='c', max_length=1),
        ),
    ]
