# Generated by Django 2.1.3 on 2018-12-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0021_auto_20181209_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='altotitulolistahijos',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='justificacionverticaltitulolistahijos',
            field=models.CharField(default='c', max_length=1),
        ),
    ]
