# Generated by Django 2.1.3 on 2018-12-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0022_auto_20181209_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='colorfondotextolista',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colortextlista',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fonttextolista',
            field=models.CharField(default='Arial,12,bold', max_length=100),
        ),
    ]
