# Generated by Django 2.1.3 on 2018-12-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0023_auto_20181209_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='colortextlista',
            new_name='colortextolista',
        ),
    ]
