# Generated by Django 2.1.3 on 2018-12-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0024_auto_20181209_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='colorfondocolumnas',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
