# Generated by Django 2.1.3 on 2018-12-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0025_modelo_colorfondocolumnas'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='altocolumnaslista',
            field=models.SmallIntegerField(default=30),
        ),
    ]
