# Generated by Django 2.1.3 on 2018-12-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0026_modelo_altocolumnaslista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='altocolumnaslista',
            new_name='altocolumnas',
        ),
    ]
