# Generated by Django 2.1.3 on 2018-12-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0027_auto_20181209_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='altocolumnaslistahijos',
            field=models.SmallIntegerField(default=30),
        ),
    ]
