# Generated by Django 2.1.3 on 2018-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0028_modelo_altocolumnaslistahijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='linkboton',
            field=models.BooleanField(default=True),
        ),
    ]
