# Generated by Django 2.1.3 on 2018-12-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0029_modelo_linkboton'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='colorbotonlinknuevo',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
