# Generated by Django 2.1.3 on 2018-11-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='textoenmenu',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
