# Generated by Django 2.1.3 on 2018-12-13 12:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialEncabezado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='tutorialdetalle',
            name='tutorialencabezado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TutorialEncabezado'),
        ),
    ]
