# Generated by Django 2.1.3 on 2018-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181213_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialdetalle',
            name='correlativo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialdetalle',
            name='diagrama',
            field=models.ImageField(blank=True, null=True, upload_to='tutorial'),
        ),
        migrations.AddField(
            model_name='tutorialencabezado',
            name='correlativo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialencabezado',
            name='diagrama',
            field=models.ImageField(blank=True, null=True, upload_to='tutorial'),
        ),
    ]
