# Generated by Django 2.1.3 on 2018-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181213_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialdetalle',
            name='correlativo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tutorialencabezado',
            name='correlativo',
            field=models.IntegerField(default=1),
        ),
    ]
