# Generated by Django 2.1.3 on 2018-11-20 19:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('tipo', models.CharField(max_length=1)),
                ('largostring', models.SmallIntegerField(default=0)),
                ('foranea', models.CharField(default='nada', max_length=30)),
                ('inicial', models.CharField(blank=True, max_length=30)),
                ('etiqueta', models.CharField(blank=True, max_length=100)),
                ('textobotones', models.CharField(blank=True, max_length=100)),
                ('enlista', models.BooleanField(default=False)),
                ('numerocolumnas', models.SmallIntegerField(default=1)),
                ('formatofecha', models.CharField(blank=True, default='', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Modelo')),
            ],
        ),
    ]
