# Generated by Django 2.1.3 on 2018-11-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='coloretiqueta',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='colortextocolumna',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='etiquetaarriba',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='fontetiqueta',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='fonttextocolumna',
            field=models.CharField(default='Arial,15,bold', max_length=100),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='textocolumna',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='textoplaceholder',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
