# Generated by Django 2.1.3 on 2018-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_auto_20181129_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='etiquetaarriba',
            field=models.BooleanField(default=True),
        ),
    ]
