# Generated by Django 2.1.3 on 2018-12-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_auto_20181129_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='justificaciontextocolumna',
            field=models.CharField(default='i', max_length=1),
        ),
    ]
