# Generated by Django 2.1.3 on 2018-12-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_propiedad_justificaciontextocolumna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='colortextocolumna',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fonttextocolumna',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='textocolumna',
        ),
    ]
