# Generated by Django 2.1.3 on 2018-12-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_auto_20181202_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='textocolumna',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
