# Generated by Django 2.1.3 on 2018-12-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_propiedad_textocolumna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='coloretiqueta',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fontetiqueta',
        ),
    ]
