# Generated by Django 2.1.3 on 2018-12-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_auto_20181204_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='textoplaceholder',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
